"""Generated cluster cards (Markdown) and ARC `servers` settings from servers.yaml."""

from __future__ import annotations

from pathlib import Path

import yaml

from .model import Server, format_walltime
from .submit import SubmitError, render_submit_script

GENERATED_SUBDIR = Path("hpc") / "servers" / "generated"

# servers.yaml scheduler -> ARC `cluster_soft` (ARC lower-cases it and accepts
# slurm / pbs / oge / sge / htcondor / local; see arc/job/ssh.py and arc/job/local.py).
ARC_CLUSTER_SOFT = {
    "slurm": "Slurm",
    "pbs": "PBS",
    "pbspro": "PBS",
    "torque": "PBS",
    "sge": "OGE",
    "htcondor": "HTCondor",
    "local": "local",
}
# ESS that ARC can submit to a server (arc/settings/settings.py `supported_ess`); psi4 is not one.
ARC_ESS = ("gaussian", "molpro", "orca", "qchem")

_EXAMPLE_INPUT = {"orca": "job.inp", "gaussian": "job.gjf", "qchem": "job.in", "molpro": "job.in",
                  "psi4": "job.in", "pyscf": "job.py"}
_SUBMIT = {"slurm": "sbatch", "local": "bash"}


def generated_dir(cfg) -> Path:
    curated = next((s.path for s in cfg.sources if s.name == "curated" and s.type == "local" and s.path), None)
    return Path(curated or Path(cfg.root) / "knowledge") / GENERATED_SUBDIR


def _fmt(v) -> str:
    if v is None or v == "":
        return "-"
    if isinstance(v, bool):
        return "yes" if v else "no"
    if isinstance(v, float) and v.is_integer():
        return str(int(v))
    return str(v)


def access_text(p) -> str:
    """'everyone' or 'users a, b; groups g' for a partition."""
    if p.access is None:
        return "everyone"
    bits = []
    if p.access.users:
        bits.append("users " + ", ".join(p.access.users))
    if p.access.groups:
        bits.append("groups " + ", ".join(p.access.groups))
    return "; ".join(bits)


def _code(v) -> str:
    return f"`{v}`" if v not in (None, "") else "-"


# ----------------------------------------------------------------- ARC settings

def arc_server_entry(server: Server) -> dict:
    part = server.default_partition
    entry: dict = {"cluster_soft": ARC_CLUSTER_SOFT[server.scheduler]}
    if server.scheduler != "local" and server.host:
        entry["address"] = server.host
    if server.arc.get("path"):
        entry["path"] = server.arc["path"]
    if part is not None:
        entry["cpus"] = part.cores_per_node
        mem = part.mem_per_node_gb
        entry["memory"] = int(mem) if float(mem).is_integer() else mem
    # ARC takes the first queue as the default one.
    ordered = sorted(server.partitions.values(), key=lambda p: not p.default)
    if ordered:
        entry["queues"] = {p.name: format_walltime(p.max_walltime_seconds) for p in ordered}
    if server.arc.get("max_simultaneous_jobs") is not None:
        entry["max_simultaneous_jobs"] = int(server.arc["max_simultaneous_jobs"])
    return entry


def arc_settings(servers: dict[str, Server], names: list[str] | None = None) -> str:
    """Python source for ~/.arc/settings.py: a `servers` dict and a suggested `global_ess_settings`."""
    names = names or list(servers)
    unknown = [n for n in names if n not in servers]
    if unknown:
        raise KeyError(f"unknown server(s) {unknown}; known: {', '.join(servers) or '(none)'}")
    lines = [
        "# Generated by `rag-drg servers arc-settings` from servers.yaml. Paste into ~/.arc/settings.py.",
        "# Add your own 'un' (username) and 'key' (path to your SSH private key) to each server;",
        "# ARC does not read ~/.ssh/config. Never commit these.",
        "servers = {",
    ]
    for n in names:
        s = servers[n]
        lines.append(f"    {n!r}: {{")
        for k, v in arc_server_entry(s).items():
            lines.append(f"        {k!r}: {v!r},")
        lines.append("        # 'un': '<your username>',")
        lines.append("        # 'key': '/home/<you>/.ssh/id_ed25519',")
        if "path" not in s.arc:
            lines.append("        # 'path': '<remote base path, e.g. /home>',  (set arc.path in servers.yaml)")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    lines.append("# Suggested; a list is a priority order. 'local' must also exist in `servers` for in-core ESS.")
    lines.append("global_ess_settings = {")
    for ess in ARC_ESS:
        having = [n for n in names if any(sw.ess == ess for sw in servers[n].software.values())]
        if having:
            val = having[0] if len(having) == 1 else having
            lines.append(f"    {ess!r}: {val!r},")
    if any(sw.ess == "pyscf" for n in names for sw in servers[n].software.values()):
        lines.append("    'pyscf': 'local',  # ARC runs PySCF in-core on the machine ARC runs on")
    lines.append("}")
    if any(sw.ess == "psi4" for n in names for sw in servers[n].software.values()):
        lines.append("# psi4 is installed but is not in ARC's supported_ess, so it has no entry here.")
    return "\n".join(lines) + "\n"


# ----------------------------------------------------------------- cards

def _example_request(server: Server, key: str) -> dict:
    parts = server.partitions_for(key)
    part = server.default_partition if server.default_partition in parts else (parts[0] if parts else None)
    gpus = 0
    if part is not None and part.gpus_per_node and (key.endswith("-gpu") or "gpu" in key.split("-")):
        gpus = 1
    return {"partition": part.name if part else None, "gpus": gpus}


def render_card(server: Server) -> str:
    s = server
    tags = ["cluster", "server", s.name, s.scheduler, "partitions", "queues", "install paths",
            "absolute paths", "scratch", "quota", "submit script", *s.software.keys()]
    meta = {
        "title": f"{s.name} cluster card (generated from servers.yaml)",
        "domain": "hpc",
        "software": s.scheduler,
        "doc_type": "card",
        "status": "draft",
        "generated": True,
        "tags": list(dict.fromkeys(tags)),
    }
    out = ["---", yaml.safe_dump(meta, sort_keys=False, allow_unicode=True, width=1000).strip(), "---",
           f"# {s.name} cluster card", "",
           "Generated by `rag-drg servers render-cards` from `servers.yaml`. Do not edit this file: "
           "change `servers.yaml` and regenerate. The MCP tools `server_info`, `render_submit_script` "
           "and `check_resources` use the same data.", ""]
    if s.description:
        out += [s.description.strip(), ""]

    out += ["## Access", ""]
    out.append(f"* Scheduler: {s.scheduler}")
    if s.host:
        out.append(f"* Login host: `{s.host}`" + (f" (ssh alias `{s.ssh_alias}`)" if s.ssh_alias else ""))
    out.append(f"* User: {'`' + s.user + '`' if s.user else 'your own account ($USER)'}; "
               "log in with SSH keys or an agent (no passwords)")
    out.append(f"* Environment modules: {'available' if s.modules_available else 'not used'}; "
               "programs are called by the absolute paths below")
    out += ["* ARC `servers` entry for `~/.arc/settings.py` (add your `un` and `key`):", "",
            "```python", arc_settings({s.name: s}).split("\n\n# Suggested")[0].strip(), "```", ""]

    out += ["## Partitions / queues", "",
            "| Name | Max walltime | Cores/node | Mem/node (GB) | GPUs/node | Max nodes | Default | Access | Notes |",
            "|---|---|---|---|---|---|---|---|---|"]
    for p in s.partitions.values():
        gpu = f"{p.gpus_per_node} x {p.gpu_type}" if p.gpus_per_node and p.gpu_type else _fmt(p.gpus_per_node or 0)
        out.append(f"| `{p.name}` | `{p.max_walltime}` | {p.cores_per_node} | {_fmt(p.mem_per_node_gb)} | {gpu} | "
                   f"{p.max_nodes} | {_fmt(p.default)} | {access_text(p)} | {p.notes or ''} |")
    out.append("")
    restricted = [p for p in s.partitions.values() if p.access is not None]
    if restricted:
        out += ["Restricted queues (servers.yaml `access:`): only the listed users, or members of ANY listed "
                "group, may submit there. Check yours with `rag-drg servers access "
                f"{s.name}` (add `--live` to ask the scheduler itself).", ""]
        for p in restricted:
            if p.access.notes:
                out.append(f"* `{p.name}`: {p.access.notes.strip()}")
        if any(p.access.notes for p in restricted):
            out.append("")

    out += ["## Installed software", "",
            "| Key | ESS | Version | Executable | Parallel | Partitions |", "|---|---|---|---|---|---|"]
    for sw in s.software.values():
        out.append(f"| `{sw.key}` | {sw.ess} | {_fmt(sw.version)} | `{sw.executable}` | {sw.parallel} | "
                   f"{', '.join(sw.partitions) or 'any'} |")
    out.append("")
    for sw in s.software.values():
        out += [f"### {sw.key} environment", ""]
        setup = [f'export {k}="{v}"' for k, v in sw.env.items()] + list(sw.setup)
        if setup:
            out += ["```bash", *setup, "```"]
        else:
            out.append("No environment setup needed; call the executable by its absolute path.")
        if sw.notes:
            out += ["", sw.notes.strip()]
        out.append("")

    out += ["## Storage, scratch and quotas", "",
            "| Area | Path | Quota (GB) | Backed up | Check usage with |", "|---|---|---|---|---|"]
    for st in s.storage:
        out.append(f"| {st.name} | `{st.path}` | {_fmt(st.quota_gb)} | {_fmt(st.backed_up)} | {_code(st.quota_command)} |")
    sc = s.scratch
    out.append(f"| scratch{' (node-local)' if sc.node_local else ''} | {_code(sc.path)} | - | no | - |")
    out.append("")
    if sc.notes:
        out += [sc.notes.strip(), ""]

    out += ["## How to submit", "",
            "Generate a filled-in script with `rag-drg servers submit "
            f"{s.name} <software-key> <input> [--cores N --mem GB --time HH:MM:SS --partition P --gpus G]` "
            "(MCP: `render_submit_script`). It checks the partition limits and prints the matching "
            "memory/core lines for the input. Examples with default resources:", ""]
    submit = _SUBMIT.get(s.scheduler, "qsub")
    for sw in s.software.values():
        out += [f"### Submit {sw.key}", ""]
        req = _example_request(s, sw.key)
        inp = _EXAMPLE_INPUT.get(sw.ess, "job.in")
        try:
            script, notes = render_submit_script(s, sw.key, inp, partition=req["partition"], gpus=req["gpus"])
        except (SubmitError, ValueError) as e:
            out += [f"Cannot render an example: {e}", ""]
            continue
        out += [f"Input lines: {notes[0].split(': ', 1)[1]}", "", "```bash", script.rstrip(), "```", "",
                f"Submit with `{submit} job.sh`.", ""]
    return "\n".join(out).rstrip() + "\n"


def render_cards(servers: dict[str, Server], out_dir: Path) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name, s in servers.items():
        path = out_dir / f"{name}.md"
        path.write_text(render_card(s))
        written.append(path)
    return written
